PORT: 5562
BROADCAST_PORT: 5563

modules:
  module1:
    valvePin: 16
    pump: pump1
    plugins:
      LED: LED1
      speaker: speaker1
      lickometer: lickometer1

  module2:
    valvePin: 17
    pump: pump1
    plugins:
      LED: LED2
      speaker: speaker2
      lickometer: lickometer2


pumps:
  pump1:
    fillValvePin: 20
    stepPin: 24 
    stepType: Half
    defaultSyringeType: BD5mL
    flushPin: 27
    revPin: 22
    dirPin: 23
    GPIOPins:
      - 5
      - 6
      - 26

plugins:
  LED1:
    type: LED
    LEDPin: 14
  speaker1:
    type: speaker
    SDPin: 3
  lickometer1:
    type: lickometer
    lickPin: 2
  LED2:
    type: LED
    LEDPin: 8
  speaker2:
    type: speaker
    SDPin: 7
  lickometer2:
    type: lickometer
    lickPin: 9
