modules:
  module1:
    valvePin: 16
    lickPin: 21
    pump: pump1

pumps:
  pump1:
    fillValve: 20
    stepPin: 24 
    stepType: Half
    defaultSyringeType: BD5mL
    flushPin: 27
    revPin: 22
    dirPin: 23
    GPIOPins:
      - 6
      - 13
      - 19