PORT: 5562
BROADCAST_PORT: 5563

modules:
  module1:
    valvePin: 10
    pump: pump1
    plugins:
      lickometer: lickometer1

  module2:
    valvePin: 11
    pump: pump1
    plugins:
      lickometer: lickometer2


pumps:
  pump1:
    fillValvePin: 2
    stepPin: 3
    stepType: Half
    defaultSyringeType: BD5mL
    flushPin: 0
    revPin: 5
    dirPin: 6
    GPIOPins:
      - 7
      - 8
      - 9

plugins:
  lickometer1:
    type: lickometer
    lickPin: 14
  lickometer2:
    type: lickometer
    lickPin: 15
