module1:
  stepPin: 24
  lickPin: 16
  stepType: "Full"
  defaultSyringeType: 'BD5mL'
  flushPin: 27
  revPin: 22
  syringe_kwargs:
    ENPin: 25
    dirPin: 23
    GPIOPins:
      M0: 6
      M1: 13
      M2: 19

module2:
  stepPin: 12
  lickPin: 17
  stepType: "Full"
  defaultSyringeType: 'BD5mL'
  flushPin: 5
  revPin: 26
  syringe_kwargs:
    ENPin: 25
    dirPin: 23
    GPIOPins:
      M0: 6
      M1: 13
      M2: 19

