clockPin: 23

# module config
modules:
  module1:
    type: DefaultModule
    dead_volume: 14
    port: port0
    pump: pump1

  module2:
    type: DefaultModule
    dead_volume: 14
    port: port1
    pump: pump1

  module3:
    type: DefaultModule
    dead_volume: 14
    port: port2
    pump: pump1

  module4:
    type: DefaultModule
    dead_volume: 14
    port: port3
    pump: pump1

  module5:
    type: DefaultModule
    dead_volume: 14
    port: port4
    pump: pump1

  module6:
    type: DefaultModule
    dead_volume: 15
    port: port5
    pump: pump1

  # module7:
  #   type: DefaultModule
  #   dead_volume: 15
  #   port: port6
  #   pump: pump1

  # module8:
  #   type: DefaultModule
  #   dead_volume: 15
  #   port: port7
  #   pump: pump1

# pump config
pumps:
  pump1:
    type: PicoPump
    syringeType: BD30mL
    port: /dev/ttyACM0
    fillValvePin: 15
  # pump1:
  #   enPin: "GPA0"
  #   fillValvePin: "GPA6"
  #   stepPin: "GPA4"
  #   stepType: Full
  #   syringeType: BD30mL
  #   flushPin: 25
  #   revPin: 16
  #   dirPin: "GPA5"
  #   modePins:
  #     - "GPA1"
  #     - "GPA2"
  #     - "GPA3"