# This file defines parameters for the creation
# of the reward interface. In this example
# all modules are configured using presets
# for the additional parameters associated to these
# presets see presets.yaml

# pin to use to detect the clock signal 
clockPin: 23

# module config
modules:
  module1:
    dead_volume: 14
    preset_name: module1
    pump: pump1
    lickBusPin: 17

  module2:
    dead_volume: 14
    preset_name: module2
    pump: pump1
    lickBusPin: 17

  module3:
    dead_volume: 14
    preset_name: module3
    pump: pump1
    lickBusPin: 17

  module4:
    dead_volume: 14
    preset_name: module4
    pump: pump1
    lickBusPin: 17

  module5:
    dead_volume: 14
    preset_name: module5
    pump: pump1
    lickBusPin: 17

  module6:
    dead_volume: 14
    preset_name: module6
    pump: pump1
    lickBusPin: 17

  module7:
    dead_volume: 14
    preset_name: module7
    pump: pump1
    lickBusPin: 17

  module8:
    dead_volume: 14
    preset_name: module8
    pump: pump1
    lickBusPin: 17

# pump config
pumps:
  pump1:
    syringeType: BD30mL
    port: /dev/ttyACM0
    fillValvePin: 15
    lead: 0.2