# odor flow controller parameters
odor_flow_controller: A
odor_flow_controller_units: CC
odor_flow_controller_max: 200

# dilutant flow controller parameters
dilutant_flow_controller: B
dilutant_flow_controller_units: LPM
dilutant_flow_controller_max: 2

# inert flow controller parameters
inert_flow_controller: C
inert_flow_controller_units: LPM
inert_flow_controller_max: 2

# valve configuration
outlet_valve: GPB5
release_valve: GPB7
initial_odor_concentration: 0.1
initial_flowrate: 1

odor_valves:
#these keys can be updated to reflect odor names
  odor1: GPA0
  odor2: GPA1
  odor3: GPA2
  odor4: GPA3
  odor5: GPA4
  odor6: GPA5
  odor7: GPB0
  odor8: GPB1
  odor9: GPB2
  odor10: GPB3
  odor11: GPB4
